### ISSUE TITLE
[BUG] Line with date and author broken after HUGO update

### ISSUE THREAD

**Issue by Chajmke** [adityatelange/hugo-PaperMod#1327]
After the latest update of HUGO v0.120.2 the line with date and author is buggy. Instead of showing the date and the name of the author, now the code is written on the page: <span title='2023-11-01 00:00:00 +0000 UTC'>01 Nov. 2023</span>&nbsp;·&nbsp;2 Minuten&nbsp;·&nbsp;AUTHOR

**Occurs** with a local instance of HUGO (Mac OS) and the version used by render.com

**Comment by woadey** [comment]
This got fixed by the latest commit: [7795c90f6fa106733267481d9ed0518b00f2c62c](https://github.com/adityatelange/hugo-PaperMod/commit/7795c90f6fa106733267481d9ed0518b00f2c62c)

**Comment by Chajmke** [comment]
Yepp. I made sure, the latest commit is activated. The error still occurs.

**Comment by adityatelange** [comment]
> Yepp. I made sure, the latest commit is activated. The error still occurs.

Can u fill the bug report template? I don't want to ask all that stuff one by one.
